### ISSUE TITLE
"System Setup" link in README 404's

### ISSUE THREAD

**Issue by mojason-81** [jifalops/crossplatform#1]
Just wanted to let you know I'm getting a 404 when clicking the link.  It's trying to take me to https://github.com/jifalops/crossplatform/blob/master/doc/setup.md

**Comment by jifalops** [comment]
Sorry this is something I had only just started. I'm not sure if it will end up being used. It may be better off as a private repo

**Comment by mojason-81** [comment]
Ah!  No worries.  Just thought I'd let you know in case you were developing it for release.
